
spring:
  application:
    name: eurekaserver-sample
  security:
    basic:
      enabled: true
    user:
      name: ms-eureka-user
      password: esru-esme-krau

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false